export const defaultState: AppState = {
  isAuthChecked: false,
  isLoading: true,
  page: null,
  user: null,
  messages: null,
  chats: null,
  chat: null,
  chatUsers: null,
  searchedUsers: null,
  loginFormError: null,
  registerFormError: null,
  changePasswordFormError: null,
  avatarFormError: null,
  profileFormError: null,
  searchUsersFormError: null,
  createChatFormError: null,
  changeChatAvatarFormError: null,
  addUsersToChatFormError: null,
  removeUsersFromChatFormError: null,
  chatToken: null,
  isMessagesLoading: true,
};
